6th_M_N_relationship2/db_ws_6_5/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('profile/<username>/', views.profile, name='profile'),
]

6th_M_N_relationship2/db_ws_6_5/libraries/urls.py
from django.urls import path
from . import views


app_name = 'libraries'

urlpatterns = [
    path('create_author/', views.create_author, name='create_author'),
    path('books/', views.books, name='books'),
    path('books/create/', views.books_create, name='books_create'),
    path('author_books/<int:author_pk>/', views.author_books, name='author_books'),
    path('author_subscribed/<int:author_pk>/', views.author_subscribed, name='author_subscribed'),
]

6th_M_N_relationship2/db_ws_6_5/novel_hub/urls.py
from django.contrib import admin
from django.urls import path, include
from libraries import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('libraries/', include('libraries.urls')),
]

6th_M_N_relationship2/db_ws_6_5/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

6th_M_N_relationship2/db_ws_6_5/libraries/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Author(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    subscribed_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='subscribed_authors')
    nickname = models.CharField(max_length=20)
    
    def __str__(self):
            return self.nickname
    
class Book(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    genre = models.CharField(max_length=10)

    

6th_M_N_relationship2/db_ws_6_5/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    
     class Meta(UserCreationForm.Meta):
        model = get_user_model()

6th_M_N_relationship2/db_ws_6_5/libraries/forms.py
from django import forms
from .models import Author, Book


class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ('nickname', )


class BookForm(forms.ModelForm):
    
    class Meta:
        model = Book
        fields = '__all__'

6th_M_N_relationship2/db_ws_6_5/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm


# Create your views here.
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('index')

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def delete(request):
    auth_logout(request)
    request.user.delete()
    return redirect('accounts:login')

def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

6th_M_N_relationship2/db_ws_6_5/libraries/views.py
from django.shortcuts import render, redirect
from .models import Author, Book
from .forms import AuthorForm, BookForm
# Create your views here.
def index(request):
    return render(request, 'libraries/index.html')

def create_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save(commit=False)
            author.user = request.user
            author.save()
            return redirect('accounts:profile', author.user.username)
    else:
        form = AuthorForm()
    context = {
        'form': form
    }
    return render(request, 'libraries/create_author.html', context)

def books(request):
    books = Book.objects.all()
    context = {
        'books': books
    }
    return render(request, 'libraries/books.html', context)

def books_create(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('libraries:books')
    else:
        form = BookForm()
    context = {
        'form': form
    }
    return render(request, 'libraries/books_create.html', context)

def author_books(request, author_pk):
    author = Author.objects.get(pk=author_pk)
    books = author.book_set.all()
    context = {
        'author': author,
        'books': books
    }
    return render(request, 'libraries/author_books.html', context)

def author_subscribed(request, author_pk):
    author = Author.objects.get(pk=author_pk)
    if author.subscribed_users.filter(pk=request.user.pk).exists():
        author.subscribed_users.remove(request.user)
    else:
        author.subscribed_users.add(request.user)
    return redirect('libraries:author_books', author.pk)

6th_M_N_relationship2/db_ws_6_5/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>LOGIN Page</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="LOGIN">
  </form>
{% endblock content %}

6th_M_N_relationship2/db_ws_6_5/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ person.username }}님의 프로필</h1>
  <a href="{% url 'libraries:create_author' %}">[작가 생성하기]</a>
  <hr>
  <h2>{{ person.username }}의 작가명 모음</h2>
  <ul>
    {% for author in person.author_set.all %}
      <li>{{ author.nickname }}</li>
    {% endfor %}
  </ul>
  <hr>
  <h2>구독중인 작가 목록</h2>
  <ul>
    {% for author in person.subscribed_authors.all %}
      <li>
        <a href="{% url "libraries:author_books" author.pk %}">{{ author.nickname }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

6th_M_N_relationship2/db_ws_6_5/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>Sign Up Page</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Sign up">
  </form>
{% endblock content %}

6th_M_N_relationship2/db_ws_6_5/libraries/templates/libraries/author_books.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ author.nickname }}의 소설 목록</h1>
  <form action="{% url 'libraries:author_subscribed' author.pk %}" method="POST">
    {% csrf_token %}
    {% if request.user in author.subscribed_users.all %}
      <input type="submit" value="구독중">
      {% else %}
      <input type="submit" value="구독">
    {% endif %}
  </form>
  <ul>
    {% for book in books %}
      <li>{{ book.title }}</li>
      <li>{{ book.genre }}</li>
      <hr>
    {% endfor %}
  </ul>

{% endblock content %}

6th_M_N_relationship2/db_ws_6_5/libraries/templates/libraries/books.html
{% extends 'base.html' %}

{% block content %}
  <h1>전체 소설 목록</h1>
  <a href="{% url 'libraries:books_create' %}">[책 쓰러 가기]</a>
  <ul>
    {% for book in books %}
      <li>{{ book.title }}</li>
      <li>
        <a href="{% url 'libraries:author_books' book.author.pk %}">
          {{ book.author.nickname }}</li>
        </a>
      <hr>
    {% endfor %}
  </ul>

{% endblock content %}

6th_M_N_relationship2/db_ws_6_5/libraries/templates/libraries/books_create.html
{% extends 'base.html' %}

{% block content %}
  <h1>책 생성 페이지</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="create">
  </form>
{% endblock content %}

6th_M_N_relationship2/db_ws_6_5/libraries/templates/libraries/create_author.html
{% extends 'base.html' %}

{% block content %}
  <h1>작가 생성 페이지</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="create">
  </form>
{% endblock content %}

6th_M_N_relationship2/db_ws_6_5/libraries/templates/libraries/index.html
{% extends 'base.html' %}

{% block content %}
<section>
  <h2>소설 연재 프로젝트를 만나보세요</h2>
  <p>소설 연재 프로젝트에 오신 것을 환영합니다. 다채로운 이야기들이 펼쳐지는 곳으로 여러분을 초대합니다. 세계 각지의 유능한 작가들이 쓴 연재 소설들을 만나보세요.</p>
  <p>챕터별로 이야기가 전개되는 재미를 느껴보고, 독자들과 함께 소통하는 활기찬 커뮤니티에서 새로운 세계에 빠져보세요. 로맨스, 미스터리, 판타지 등 다양한 장르의 흥미로운 이야기들이 여러분의 취향에 맞게 준비되어 있습니다.</p>
  <p>새로운 이야기를 발견하고 작가들과 소통하며 창작을 지원하는 즐거움을 경험해보세요. 독자와 작가로 이루어진 우리의 성장하는 커뮤니티에 가입하고, 오늘부터 짜릿한 문학의 여정에 동참해보세요!</p>
  <button class="cta-button">지금 시작하기</button>
</section>
{% endblock content %}

6th_M_N_relationship2/db_ws_6_5/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <a href="{% url 'index' %}">[메인 페이지]</a>
  {% if request.user.is_authenticated %}
    <h3>반갑습니다. {{ user.username }}님!</h3>
    <a href="{% url 'accounts:profile' user.username %}">[내 프로필]</a>
    <form action="{% url 'accounts:logout' %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="Logout">
    </form>
    <form action="{% url 'accounts:delete' %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="회원탈퇴">
    </form>
  {% else %}
    <h3>로그인 해 주세요.</h3>
    <a href="{% url 'accounts:login' %}">[Login]</a>
    <a href="{% url 'accounts:signup' %}">[Sign Up]</a>
  {% endif %}
  <hr>
  <a href="{% url 'libraries:books' %}">[소설 보러 가기]</a>
  
  {% block content %}
  {% endblock content %}
</body>
</html>