4th_1_N_relationship2/db_ws_4_5/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('staff/<int:pk>/', views.staff, name='staff'),
    path('staff/<int:pk>/delete/', views.delete, name='delete'),
]

4th_1_N_relationship2/db_ws_4_5/convenience_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stores/', include('stores.urls')),
    path('accounts/', include('accounts.urls')),
]

4th_1_N_relationship2/db_ws_4_5/stores/urls.py
from django.urls import path
from . import views


app_name = 'stores'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:store_pk>/', views.detail, name='detail'),
    path('create/', views.stores_create, name='stores_create'),
    path('<int:store_pk>/products_create/', views.products_create, name='products_create'),
    path('<int:store_pk>/products/<int:product_pk>/delete/', views.products_delete, name='products_delete'),
]

4th_1_N_relationship2/db_ws_4_5/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

4th_1_N_relationship2/db_ws_4_5/stores/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Store(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    is_franchise = models.BooleanField()

class Product(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    amount = models.IntegerField()
    price = models.IntegerField()
    adult = models.BooleanField()

4th_1_N_relationship2/db_ws_4_5/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    
     class Meta(UserCreationForm.Meta):
        model = get_user_model()


class CustomUserChangeForm(UserChangeForm):
    
    class Meta(UserChangeForm):
        model = get_user_model()
        fields = ('first_name', 'last_name',)


class CustomUserStaffForm(UserChangeForm):
    
    class Meta(UserChangeForm):
        model = get_user_model()
        fields = ('is_staff',)

4th_1_N_relationship2/db_ws_4_5/stores/forms.py
from django import forms
from .models import Store, Product


class StoreForm(forms.ModelForm):

    class Meta:
        model = Store
        fields = '__all__'

class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        exclude = ('store', 'user',)

4th_1_N_relationship2/db_ws_4_5/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomUserStaffForm
from .models import User as auth_user
User = get_user_model()
# Create your views here.
def index(request):
    members = User.objects.all()
    context = {
        'members': members
    }
    return render(request, 'accounts/index.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('stores:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    if request.method == 'POST':
        auth_logout(request)
    return redirect('accounts:login')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('stores:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)

def staff(request, pk):
    member = auth_user.objects.get(pk=pk)
    if request.method == 'POST':
        form = CustomUserStaffForm(request.POST, instance=member)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
        else:
            print(form.errors)
    else:
        form = CustomUserStaffForm(instance=member)
    context = {
        'form': form,
    }
    return render(request, 'accounts/staff.html', context)

def delete(request, pk):
    member = auth_user.objects.get(pk=pk)
    member.delete()
    return redirect('accounts:index')

4th_1_N_relationship2/db_ws_4_5/stores/views.py
from django.shortcuts import render, redirect
from .models import Store, Product
from .forms import StoreForm, ProductForm

# Create your views here.
def index(request):
    stores = Store.objects.all()
    context = {
        'stores': stores
    }
    return render(request, 'stores/index.html', context)

def detail(request, store_pk):
    store = Store.objects.get(pk=store_pk)
    products = store.product_set.all()
    products_form = ProductForm()
    context = {
        'store': store,
        'products': products,
        'products_form': products_form
    }
    return render(request, 'stores/detail.html', context)

def stores_create(request):
    if request.method == 'POST':
        form = StoreForm(request.POST)
        if form.is_valid():
            store = form.save()
            return redirect('stores:detail', store.pk)
    else:
        form = StoreForm()
    context = {
        'form': form
    }
    return render(request, 'stores/stores_create.html', context)

def products_create(request, store_pk):
    store = Store.objects.get(pk=store_pk)
    if request.method == 'POST':
        products_form = ProductForm(request.POST)
        if products_form.is_valid():
            product = products_form.save(commit=False)
            product.store = store
            product.user = request.user
            product.save()
        else:
            context = {
                'store': store,
                'products_form': products_form
            }
            return render(request, 'stores/detail.html', context)
    return redirect('stores:detail', store.pk)


def products_delete(request, store_pk, product_pk):
    store = Store.objects.get(pk=store_pk)
    product = Product.objects.get(pk=product_pk)
    if request.method == 'POST':
        if request.user == product.user:
            product.delete()
    return redirect('stores:detail', store.pk)

4th_1_N_relationship2/db_ws_4_5/accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>직원 전체 목록</h1>
  <ul>
    {% for member in members %}
      <li>이름 : {{ member.username }}</li>
      <li>admin 여부 : {{ member.is_superuser }}</li>
      <li>staff 여부 : {{ member.is_staff }}</li>
      {% if user.is_staff %}
        <a href="{% url 'accounts:update' %}">회원 정보 수정</a>
      {% endif %}
      {% if user.is_superuser %}
      <a href="{% url "accounts:staff" member.pk %}">관리자 여부 수정</a>
      <form action="{% url "accounts:delete" member.pk %}">
        <input type="submit" value='회원 삭제'>
      </form>{% endif %}
      <hr>
    {% endfor %}
  </ul>
{% endblock content %}

4th_1_N_relationship2/db_ws_4_5/accounts/templates/accounts/staff.html
{% extends 'base.html' %}

{% block content %}
  <h1>관리자 여부 수정</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정">
  </form>
{% endblock content %}

4th_1_N_relationship2/db_ws_4_5/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원 정보 수정</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정">
  </form>
{% endblock content %}

4th_1_N_relationship2/db_ws_4_5/stores/templates/stores/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>편의점 상세 정보</h1>
  <p>점장 : {{ store.user }}</p>
  <p>주소 : {{ store.address }}</p>
  <p>체인점 여부 : {{ store.is_franchise }}</p>
  {% if store.user == request.user %}
    <hr>
    <h3>신규 상품 등록</h3>
    <form action="{% url 'stores:products_create' store.pk %}" method="POST">
      {% csrf_token %}
      {{ products_form.as_p }}
      <input type="submit" value="물품 등록">
    </form>
  {% endif %}
  <hr>
  <h3>전체 상품 목록</h3>
  <ul>
    {% for product in products %}
      <li>이름 : {{ product.name }}</li>
      <li>가격 : {{ product.price }}</li>
      {% if product.user == user %}
        <form action="{% url 'stores:products_delete' store.pk product.pk %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="DELETE">
        </form>
      {% endif %}
    {% endfor %}
  </ul>
  <a href="{% url 'stores:index' %}">[돌아가기]</a>
{% endblock content %}

4th_1_N_relationship2/db_ws_4_5/stores/templates/stores/index.html
{% extends 'base.html' %}

{% block content %}
<h1>전체 편의점 목록</h1>

<ul>
  {% for store in stores %}
  <a href="{% url 'stores:detail' store.pk %}">
    <li>점장 : {{ store.user.username }}</li>
    <li>주소 : {{ store.address }}</li>
  </a>
  <hr>
  {% endfor %}
</ul>
{% endblock content %}

4th_1_N_relationship2/db_ws_4_5/stores/templates/stores/stores_create.html
{% extends 'base.html' %}

{% block content %}
  <h1>신규 매장 등록 페이지</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="등록">
  </form>
  <a href="{% url 'stores:index' %}">[돌아가기]</a>
{% endblock content %}

4th_1_N_relationship2/db_ws_4_5/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% if request.user.is_authenticated %}
    <h3>반갑습니다. {{ user.username }}님!</h3>
    <form action="{% url 'accounts:logout' %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="Logout">
    </form>
    {% if user.is_staff %}
    <a href="{% url 'accounts:index' %}">[전체 직원 목록]</a>
    {% endif %}
    <a href="{% url 'stores:index' %}">[전체 매장 목록]</a>
  {% else %}
    <h3>로그인 해 주세요.</h3>
    <a href="{% url 'accounts:login' %}">[Login]</a>
    <a href="{% url 'accounts:signup' %}">[Sign Up]</a>
  {% endif %}
  
  {% block content %}
  {% endblock content %}
</body>
</html>