3rd_1_N_relationship1/restaurant_management/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('restaurants/', include('restaurants.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

3rd_1_N_relationship1/restaurants/urls.py
from django.urls import path
from . import views


app_name = 'restaurants'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:restaurant_pk>/', views.detail, name='detail'),
    path('<int:restaurant_pk>/menus/create/', views.menus_create, name='menus_create'),
    path('<int:restaurant_pk>/menus/<int:menu_pk>/update/', views.menus_update, name='menus_update'),
]

3rd_1_N_relationship1/restaurants/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=20)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.name

class Restaurant(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    descriptions = models.TextField()
    address = models.CharField(max_length=200)
    opening_time = models.TimeField()
    closing_time = models.TimeField()

class Menu(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    is_vegan = models.BooleanField()

3rd_1_N_relationship1/restaurants/forms.py
from django import forms
from .models import Restaurant, Menu


class RestaurantForm(forms.ModelForm):
    
    class Meta:
        model = Restaurant
        fields = '__all__'

        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '레스토랑 이름을 입력하세요'}),
            'Descriptions': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'placeholder': '설명을 입력하세요'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '주소를 입력하세요'}),
            'opening_time': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
            'closing_time': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
        }

class MenuForm(forms.ModelForm):
    
    class Meta:
        model = Menu
        exclude = ('restaurant', )

        widgets = {
            'name' : forms.TextInput(attrs={
                'class' : 'form-control'
            }),
            'price' : forms.TextInput(attrs={'class' : 'form-control'})
        }
class MenuUpdateForm(forms.ModelForm):

    class Meta:
        model = Menu
        exclude = ('restaurant', 'name',)

        widgets = {
            'price' : forms.TextInput(attrs={'class' : 'form-control'})
        }

3rd_1_N_relationship1/restaurants/views.py
from django.shortcuts import render, redirect
from .models import Restaurant, Menu
from .forms import RestaurantForm, MenuForm, MenuUpdateForm

# Create your views here.
def index(request):
    restaurants = Restaurant.objects.all()
    context = {
        'restaurants': restaurants
    }
    return render(request, 'restaurants/index.html', context)

def create(request):
    if request.method == 'POST':
        form = RestaurantForm(request.POST)
        if form.is_valid():
            restaurant = form.save()
            return redirect('restaurants:detail', restaurant.pk)
    else:
        form = RestaurantForm()
    context = {
        'form': form
    }
    return render(request, 'restaurants/create.html', context)

def detail(request, restaurant_pk):
    restaurant = Restaurant.objects.get(pk=restaurant_pk)
    menus = restaurant.menu_set.all()
    menu_form = MenuForm()
    context = {
        'restaurant': restaurant,
        'menus':menus,
        'menu_form': menu_form
    }
    return render(request, 'restaurants/detail.html', context)

def menus_create(request, restaurant_pk):
    restaurant = Restaurant.objects.get(pk=restaurant_pk)
    if request.method == 'POST':
        menu_form = MenuForm(request.POST)
        if menu_form.is_valid():
            menu = menu_form.save(commit=False)
            menu.restaurant = restaurant
            menu.save()
        else:
            menu_form = MenuForm()
            context = {
                'restaurant': restaurant,
                'menu_form': menu_form
            }
            return render(request, 'restaurants/detail.html', context)
    return redirect('restaurants:detail', restaurant_pk)

def menus_update(request, restaurant_pk, menu_pk):
    restaurant = Restaurant.objects.get(pk=restaurant_pk)
    menu = Menu.objects.get(pk=menu_pk)
    if request.method == 'POST':
        form = MenuUpdateForm(request.POST, instance=menu)
        if form.is_valid():
            form.save()
            return redirect('restaurants:detail', restaurant.pk)
    else:
        form = MenuUpdateForm(instance=menu)
    context = {
        'restaurant': restaurant,
        'form': form
    }
    return render(request, 'restaurants/menu_update.html', context)

3rd_1_N_relationship1/restaurants/templates/restaurants/create.html
{% extends 'base.html' %}

{% block content %}
<h1>신규 레스토랑 등록</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="등록">
</form>
<a href="{% url 'restaurants:index' %}">[돌아가기]</a>
{% endblock content %}

3rd_1_N_relationship1/restaurants/templates/restaurants/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>레스토랑 상세 정보</h1>

<p>등록 번호 : {{ restaurant.pk }}</p>
<p>종류 : {{ restaurant.category }}</p>
<p>이름 : {{ restaurant.name }}</p>
<p>주소 : {{ restaurant.address }}</p>
<p>여는 시간 : {{ restaurant.opening_time }}</p>
<p>닫는 시간 : {{ restaurant.closing_time }}</p>
<hr>
<p>{{ restaurant.descriptions }}</p>
<hr>
<h3>신규 메뉴 등록</h3>
<form action="{% url 'restaurants:menus_create' restaurant.pk %}" method="POST">
  {% csrf_token %}
  {{ menu_form.as_p }}
  <input type="submit" value="메뉴 등록">
</form>
<hr>
<h3>전체 메뉴 목록</h3>
<ul>
  {% for menu in menus %}
    <li>이름 : {{ menu.name }}</li>
    <li>가격 : {{ menu.price }}</li>
    <a href="{% url 'restaurants:menus_update' restaurant.pk menu.pk %}">[메뉴 정보 수정]</a>
  {% endfor %}
</ul>
<a href="{% url 'restaurants:index' %}">[돌아가기]</a>
{% endblock content %}

3rd_1_N_relationship1/restaurants/templates/restaurants/index.html
{% extends 'base.html' %}

{% block content %}
<h1>레스토랑 전체 목록</h1>
<a href="{% url 'restaurants:create' %}">[신규 레스토랑 등록]</a>

<ul>
  {% for restaurant in restaurants %}
    <a href="{% url 'restaurants:detail' restaurant.pk %}">
      <li>이름 : {{ restaurant.name }}</li>
      {% if restaurant.category.image %}
      <img src=" {{restaurant.category.image.url}} " alt="" style="width: 100px; height: auto;">
      {% else %}
      <li>종류 : {{restaurant.category}} </li>
      <p>이미지가 없습니다.</p>
      {% endif %}
      <li>보유중인 메뉴 수 : {{ restaurant.menu_set.all|length }}</li>
    </a>
    <hr>
  {% endfor %}
</ul>
{% endblock content %}

3rd_1_N_relationship1/restaurants/templates/restaurants/menu_update.html
{% extends 'base.html' %}

{% block content %}
<h1>메뉴 정보 수정 페이지</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="정보 수정">
</form>
<a href="{% url 'restaurants:detail' restaurant.pk %}">[돌아가기]</a>
{% endblock content %}

3rd_1_N_relationship1/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class='container'>

      {% block content %}{% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>